<template>
    <div>
        <ul class="space-y-3 pb-[43px]">
            <li>
                <p @click="answer1 = !answer1" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">
                    Which characters were adapted from Marvel's Iron Man comic books?
                </p>
                <p v-if="answer1" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px] ">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>
            </li>
            <li>
                <p @click="answer2 = !answer2" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">Why was the fighter pilot's chute jammed during the "training exercise" scene?</p>
                <p v-if="answer2" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>
            </li>
            <li>
                <p @click="answer3 = !answer3" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">Which characters were adapted from Marvel's Iron Man comic books?</p>
                <p v-if="answer3" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
            <li>
                <p @click="answer4 = !answer4" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">What is 'Iron Man' about?</p>
                <p v-if="answer4" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
            <li>
                <p @click="answer5 = !answer5" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">Is "Iron Man” based on a book?</p>
                <p v-if="answer5" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
            <li>
                <p @click="answer6 = !answer6" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">Who or what is the Invincible Iron Man?</p>
                <p v-if="answer6" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
            <li>
                <p @click="answer7 = !answer7" for="show-answer"  class="cursor-pointer text-md font-bold md:text-lg">Can Iron Man be considered a cyborg?</p>
                <p v-if="answer7" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
            <li>
                <p @click="answer8 = !answer8" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">What kind of jet is Tony Stark's private jet?</p>
                <p v-if="answer8" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
            <li>
                <p @click="answer9 = !answer9" for="show-answer" class="cursor-pointer text-md font-bold md:text-lg">Who are the villain(s) in 'Iron Man'?</p>
                <p v-if="answer9" class="border-l-4 border-accent-color pl-6 mt-[18px] text-[12px] leading-[14px] opacity-60 md:pl-[28px] md:mt-1.5 md:text-sm md:leading-[19px]">
                    For this list only the creators of the characters first appearances are listed. As with all comic book characters, Iron Man and his supporting cast have had several reinventions and different contributions from different writers. Theses include different iterations in different mediums that all have added different concepts to the overall mythology of the characters.Theirs Anthony Edward "Tony" Stark, referred to as Tony Stark. He made his first appearance in the comic story "Iron Man Is Born!" Tales of Suspense #39 (March 1963) by writers & Larry Lieber and artists Don Heck & Jack Kirby.Colonel James Rupert "Rhodey" Rhodes, referred to as Rhodey Rhodes on screen. He made his first appearance in the comic story "At the Mercy of My Foes Friends!" from Iron Man #118 (January 1979) by writer David Michelinie, writer/artist Bob Layton and artist John Byrne.Obadiah Stane, who made his first appearance in the comic story "Knight's Errand" from Iron Man #163 (October 1982) by writer Denny O'Neil and artist Luke McDonnell.Virginia "Pepper" Potts, referred to as Pepper Potts on screen. She made her first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Christine Everhart, who made her first appearance in the comic story "The Best Defense - Part Three: Technology" from Iron Man Volume 3 #75 by writer John Jackson Miller and artist Jorge Lucas.J.A.R.V.I.S. (Just A Rather Very Intelligent System) is based on the comic book character of Edwin Jarvis. Edwin Jarvis made his first appeared in the comic story "Captain America" from Tales of Suspense #59 (November 1964) by writer Stan Lee and artist Jack Kirby.Harold Joseph "Happy" Hogan, referred to as Happy Hogan on screen. He made his first appearance in the comic story "The Icy Fingers of Jack Frost!" from Tales of Suspense #45 (September 1963) by writers Stan Lee & Robert Bernstein and artist Don Heck.Howard Anthony Walter Stark, referred to as Howard Stark on screen. He made his first appearance in the comic story "The Controller Lives!" from Iron Man #28 (August 1970) by writer Archie Goodwin and artist Don Heck.and Nicholas Joseph "Nick" Fury, referred to as Nick Furry on screen. He made his first appearance in the comic story Sergeant Fury and his Howling Commandos #1 (May 1963) by writer Stan Lee and artist Jack Kirby.All other characters were created just for the film by the movie's writers.
                </p>

            </li>
        </ul>
    </div>
</template>

<script>

export default {
    data() {
        return {
            answer1: false,
            answer2: false,
            answer3: false,
            answer4: false,
            answer5: false,
            answer6: false,
            answer7: false,
            answer8: false,
            answer9: false,
        }
    },
}
    
</script>